### ISSUE TITLE
Please, clean the nodes.py

### ISSUE THREAD

**Issue by tamas-hortobagyi-deltatre** [TeaCrab/ComfyUI-TeaNodes#1]
Hi, there are a couple of leftover lines after the `class MaskBG_DIS` has been commented out.
Line 9: `from .isnet import dis_process` should be removed, I guess.
Line 230: `"TC_MaskBG_DIS": MaskBG_DIS,` detto.

Could you please fix these?

Many thanks,
Tamas

**Comment by TeaCrab** [comment]
Repo is cleaned up now.
